on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    # name: Snowsql Test
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2
    #     with:
    #       fetch-depth: 0

    #   - name: Setup NodeJS 14
    #     uses: actions/setup-node@v1
    #     with:
    #       node-version: 14
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
      - name: Testing
        uses: evarevear/snowsql-formatter-action@main
      - name: WHY
        run: echo "woooork"
      - name: Commit files
        run: |
          git config --local user.email "<githubusername>@users.noreply.github.com"
          git config --local user.name "SQL Reformat Bot"
          git commit --all -m"Reformat SQL Files to common format." || true
      - name: Push
        run: git push "https://${{github.actor}}:${{secrets.SOURCE_PUSH_TOKEN}}@github.com/${{github.repository}}.git" "${{ github.ref }}"
      

      # Checkout the source code so we have some files to look at.
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      # Run the reformat action
      # - name: Reformat SQL Files
      #   uses: evarevear/snowsql-formatter-action@master